### ISSUE TITLE
Problems initializing

### ISSUE THREAD

**Issue by rookey** [iriven/GeoIP2Country#2]
I've copied the script to my server and tried to run it a first time, pulling my local IP's country.
However, no IP data was downloaded, only the subdirectory "GeoIPDatas" created. I've changed directory rights to "777", script now returned "IP Ranges provider file not found in /var/www/vhosts/mydomain.com/httpdocs/inc/GeoIPCountry.php on line 282 

I've copied the subdirectory included in the package to the subdirectory - then the function gave a result, but incorrect country returned. Might have to do with outdated state - so I called  $IP2Country->Admin()->updateDatabase();  in the code, but it didn't seem to do anything?

**Comment by YoussefE123** [comment]
Unfortunately, the database sources from [software77.net](http://software77.net/geo-ip/) are no longer available, and I only  found out about it when I recently tried to update my files. According to [this geoiploc library](http://chir.ag/projects/geoiploc), it seems the last update was around October 2020.

**Comment by iriven** [comment]
A new version is now available based on ICANN (Internet Corporation for Assigned Names and Numbers) databases

**Comment by iriven** [comment]
A new version is now available based on ICANN (Internet Corporation for Assigned Names and Numbers) databases
